[package]
name = "rust_my_pbrt"
version = "0.1.0"
authors = ["hatuki"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]